version: 2
project_name: terraform-provider-orbstack

before:
  hooks:
    - go mod tidy

builds:
  - id: provider
    main: ./cmd/terraform-provider-orbstack
    env:
      - CGO_ENABLED=0
    goos: [darwin]
    goarch: [arm64, amd64]
    binary: terraform-provider-orbstack_v{{ .Version }}

archives:
  - id: zip
    builds: [provider]
    formats: [zip]
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    wrap_in_directory: false

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256

signs:
  - id: sign-checksums
    cmd: gpg
    artifacts: checksum
    signature: "${artifact}.sig"
    args:
      - --batch
      - --yes
      - --pinentry-mode
      - loopback
      - --passphrase-file
      - '{{ .Env.GPG_PASSPHRASE_FILE }}'
      - --detach-sign
      - --output
      - '${signature}'
      - '${artifact}'

release:
  draft: false
  prerelease: false


