name: Release with GoReleaser

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Prepare passphrase file
        run: |
          echo -n "" > pass.txt
          git status --porcelain

      - name: Import GPG key (if provided)
        run: |
          if [ -n "${GPG_PRIVATE_KEY}" ]; then
            echo "Importing GPG key"
            echo "$GPG_PRIVATE_KEY" | gpg --batch --yes --import
          else
            echo "No GPG key provided; skipping import"
          fi
          if [ -n "${GPG_PASSPHRASE}" ]; then
            echo "$GPG_PASSPHRASE" > pass.txt
          fi
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
            version: latest
            args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_PASSPHRASE_FILE: pass.txt


